[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
#opbnb = "https://opbnb-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3"
opbnb = "https://opbnb-testnet-rpc.bnbchain.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
